steps:
  # Yarn install
  #- name: 'gcr.io/${PROJECT_ID}/ubuntu-node-python:22.0.4-3.10-16.17'
  - name: 'ubuntu:latest'
    entrypoint: 'pwd'
    #args: ['install', '--frozen-lockfile', '--network-timeout', '300000']
  # Yarn tsc
  - name: 'ubuntu:latest'
    entrypoint: 'ls'
    args: ['-al']
