steps:
  # Yarn install
  - name: 'node:16-bullseye-slim'
    #- name: 'paketobuildpacks/yarn'
    entrypoint: 'yarn'
    args: ['install', '--network-timeout', '300000']
  # Yarn tsc
  - name: 'node:16-bullseye-slim'
    entrypoint: 'yarn'
    args: ['tsc']
  # Yarn build
  - name: 'node:16-bullseye-slim'
    entrypoint: 'yarn'
    args: ['build:backend']
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'image',
        'build',
        '.',
        '-f',
        'packages/backend/Dockerfile',
        '-t',
        'gcr.io/${PROJECT_ID}/backstage:xtech-micro-${COMMIT_SHA}',
        '-t',
        'gcr.io/${PROJECT_ID}/backstage:xtech-micro',
      ]
